import {
  RelationKind,
  VisualTone,
  VisualWeight,
  entityId,
  processId,
  processStepId,
  relationId,
  type MechanismModel,
  type MechanismProcess,
} from './core';

export const INNODB_STRUCTURE_ENTITIES = {
  innodb: entityId('innodb.structure.engine'),
  tablespace: entityId('innodb.structure.tablespace'),
  segment: entityId('innodb.structure.segment'),
  extent: entityId('innodb.structure.extent'),
  page: entityId('innodb.structure.page'),
  row: entityId('innodb.structure.row'),
  rowTrxId: entityId('innodb.structure.row.trx-id'),
  rowRollPointer: entityId('innodb.structure.row.roll-pointer'),
  bufferPool: entityId('innodb.structure.buffer-pool'),
  adaptiveHashIndex: entityId('innodb.structure.adaptive-hash-index'),
  changeBuffer: entityId('innodb.structure.change-buffer'),
  logBuffer: entityId('innodb.structure.log-buffer'),
  osCache: entityId('innodb.structure.os-cache'),
  systemTablespace: entityId('innodb.structure.system-tablespace'),
  doublewriteFiles: entityId('innodb.structure.doublewrite-files'),
  undoTablespaces: entityId('innodb.structure.undo-tablespaces'),
  redoLog: entityId('innodb.structure.redo-log'),
  filePerTableTablespaces: entityId('innodb.structure.file-per-table-tablespaces'),
  generalTablespaces: entityId('innodb.structure.general-tablespaces'),
  temporaryTablespaces: entityId('innodb.structure.temporary-tablespaces'),
} as const;

export const INNODB_STRUCTURE_RELATIONS = {
  engineOwnsTablespace: relationId('innodb.structure.engine-owns-tablespace'),
  engineOwnsBufferPool: relationId('innodb.structure.engine-owns-buffer-pool'),
  engineOwnsLogBuffer: relationId('innodb.structure.engine-owns-log-buffer'),
  tablespaceHasSystemKind: relationId('innodb.structure.tablespace-has-system-kind'),
  tablespaceContainsSegment: relationId('innodb.structure.tablespace-contains-segment'),
  segmentContainsExtent: relationId('innodb.structure.segment-contains-extent'),
  extentContainsPage: relationId('innodb.structure.extent-contains-page'),
  pageContainsRow: relationId('innodb.structure.page-contains-row'),
  rowContainsTrxId: relationId('innodb.structure.row-contains-trx-id'),
  rowContainsRollPointer: relationId('innodb.structure.row-contains-roll-pointer'),
  bufferPoolCachesPage: relationId('innodb.structure.buffer-pool-caches-page'),
  bufferPoolUsesAdaptiveHash: relationId('innodb.structure.buffer-pool-uses-adaptive-hash'),
  bufferPoolUsesChangeBuffer: relationId('innodb.structure.buffer-pool-uses-change-buffer'),
  adaptiveHashIndexesBufferPool: relationId('innodb.structure.adaptive-hash-index-indexes-buffer-pool'),
  changeBufferCachesSecondaryChanges: relationId('innodb.structure.change-buffer-caches-secondary-changes'),
  logBufferFlushesRedo: relationId('innodb.structure.log-buffer-flushes-redo'),
  bufferPoolFlushesThroughOsCache: relationId('innodb.structure.buffer-pool-flushes-through-os-cache'),
  osCacheFlushesSystemTablespace: relationId('innodb.structure.os-cache-flushes-system-tablespace'),
  bufferPoolWritesDoublewrite: relationId('innodb.structure.buffer-pool-writes-doublewrite'),
  systemTablespaceStoresChangeBuffer: relationId('innodb.structure.system-tablespace-stores-change-buffer'),
  undoStoresRollbacks: relationId('innodb.structure.undo-stores-rollbacks'),
  redoProtectsRecovery: relationId('innodb.structure.redo-protects-recovery'),
  tableLivesInFilePerTable: relationId('innodb.structure.table-lives-in-file-per-table'),
  tableLivesInGeneralTablespace: relationId('innodb.structure.table-lives-in-general-tablespace'),
  tempLivesInTemporaryTablespace: relationId('innodb.structure.temp-lives-in-temporary-tablespace'),
} as const;

export const innodbStructureModel: MechanismModel = {
  entities: [
    {
      id: INNODB_STRUCTURE_ENTITIES.innodb,
      label: 'InnoDB engine',
      note: 'Owns the physical hierarchy and the memory-to-disk write surfaces.',
    },
    {
      id: INNODB_STRUCTURE_ENTITIES.tablespace,
      label: 'Tablespace',
      note: 'Top storage container for segments.',
    },
    {
      id: INNODB_STRUCTURE_ENTITIES.segment,
      label: 'Segment',
      note: 'Allocates extents for indexes and related structures.',
    },
    {
      id: INNODB_STRUCTURE_ENTITIES.extent,
      label: 'Extent',
      note: 'Group of pages allocated together.',
    },
    {
      id: INNODB_STRUCTURE_ENTITIES.page,
      label: 'Page',
      note: 'Fixed-size I/O and cache unit holding records.',
    },
    {
      id: INNODB_STRUCTURE_ENTITIES.row,
      label: 'Row',
      note: 'Record body plus hidden MVCC fields.',
    },
    {
      id: INNODB_STRUCTURE_ENTITIES.rowTrxId,
      label: 'DB_TRX_ID',
      note: 'Hidden transaction id stored in the row.',
    },
    {
      id: INNODB_STRUCTURE_ENTITIES.rowRollPointer,
      label: 'DB_ROLL_PTR',
      note: 'Hidden rollback pointer to undo history.',
    },
    {
      id: INNODB_STRUCTURE_ENTITIES.bufferPool,
      label: 'Buffer Pool',
      note: 'In-memory cache of InnoDB pages.',
    },
    {
      id: INNODB_STRUCTURE_ENTITIES.adaptiveHashIndex,
      label: 'Adaptive Hash Index',
      note: 'Memory index over hot Buffer Pool access patterns.',
    },
    {
      id: INNODB_STRUCTURE_ENTITIES.changeBuffer,
      label: 'Change Buffer',
      note: 'Buffers secondary-index changes before they merge into pages.',
    },
    {
      id: INNODB_STRUCTURE_ENTITIES.logBuffer,
      label: 'Log Buffer',
      note: 'Memory surface for redo records before flush.',
    },
    {
      id: INNODB_STRUCTURE_ENTITIES.osCache,
      label: 'Operating System Cache',
      note: 'Optional I/O path between memory and disk depending on settings.',
    },
    {
      id: INNODB_STRUCTURE_ENTITIES.systemTablespace,
      label: 'System Tablespace',
      note: 'ibdata files, including system-level structures such as change buffer.',
    },
    {
      id: INNODB_STRUCTURE_ENTITIES.doublewriteFiles,
      label: 'Doublewrite Files',
      note: 'Durability guard against torn page writes.',
    },
    {
      id: INNODB_STRUCTURE_ENTITIES.undoTablespaces,
      label: 'Undo Tablespaces',
      note: 'Undo log storage used for rollback and consistent reads.',
    },
    {
      id: INNODB_STRUCTURE_ENTITIES.redoLog,
      label: 'Redo Log',
      note: 'Durable recovery log files.',
    },
    {
      id: INNODB_STRUCTURE_ENTITIES.filePerTableTablespaces,
      label: 'File-per-table Tablespaces',
      note: 'Per-table .ibd files when innodb_file_per_table is enabled.',
    },
    {
      id: INNODB_STRUCTURE_ENTITIES.generalTablespaces,
      label: 'General Tablespaces',
      note: 'Shared .ibd tablespaces that can contain multiple tables.',
    },
    {
      id: INNODB_STRUCTURE_ENTITIES.temporaryTablespaces,
      label: 'Temporary Tablespaces',
      note: 'Global and session temporary tablespace files.',
    },
  ],
  relations: [
    {
      id: INNODB_STRUCTURE_RELATIONS.engineOwnsTablespace,
      kind: RelationKind.Contains,
      source: INNODB_STRUCTURE_ENTITIES.innodb,
      target: INNODB_STRUCTURE_ENTITIES.tablespace,
      label: 'owns',
    },
    {
      id: INNODB_STRUCTURE_RELATIONS.engineOwnsBufferPool,
      kind: RelationKind.Contains,
      source: INNODB_STRUCTURE_ENTITIES.innodb,
      target: INNODB_STRUCTURE_ENTITIES.bufferPool,
      label: 'keeps memory',
    },
    {
      id: INNODB_STRUCTURE_RELATIONS.engineOwnsLogBuffer,
      kind: RelationKind.Contains,
      source: INNODB_STRUCTURE_ENTITIES.innodb,
      target: INNODB_STRUCTURE_ENTITIES.logBuffer,
      label: 'keeps log memory',
    },
    {
      id: INNODB_STRUCTURE_RELATIONS.tablespaceHasSystemKind,
      kind: RelationKind.Contains,
      source: INNODB_STRUCTURE_ENTITIES.tablespace,
      target: INNODB_STRUCTURE_ENTITIES.systemTablespace,
      label: 'system kind',
    },
    {
      id: INNODB_STRUCTURE_RELATIONS.tablespaceContainsSegment,
      kind: RelationKind.Contains,
      source: INNODB_STRUCTURE_ENTITIES.tablespace,
      target: INNODB_STRUCTURE_ENTITIES.segment,
      label: 'contains',
    },
    {
      id: INNODB_STRUCTURE_RELATIONS.segmentContainsExtent,
      kind: RelationKind.Contains,
      source: INNODB_STRUCTURE_ENTITIES.segment,
      target: INNODB_STRUCTURE_ENTITIES.extent,
      label: 'allocates',
    },
    {
      id: INNODB_STRUCTURE_RELATIONS.extentContainsPage,
      kind: RelationKind.Contains,
      source: INNODB_STRUCTURE_ENTITIES.extent,
      target: INNODB_STRUCTURE_ENTITIES.page,
      label: 'contains',
    },
    {
      id: INNODB_STRUCTURE_RELATIONS.pageContainsRow,
      kind: RelationKind.Contains,
      source: INNODB_STRUCTURE_ENTITIES.page,
      target: INNODB_STRUCTURE_ENTITIES.row,
      label: 'stores',
    },
    {
      id: INNODB_STRUCTURE_RELATIONS.rowContainsTrxId,
      kind: RelationKind.Contains,
      source: INNODB_STRUCTURE_ENTITIES.row,
      target: INNODB_STRUCTURE_ENTITIES.rowTrxId,
      label: 'has',
    },
    {
      id: INNODB_STRUCTURE_RELATIONS.rowContainsRollPointer,
      kind: RelationKind.Contains,
      source: INNODB_STRUCTURE_ENTITIES.row,
      target: INNODB_STRUCTURE_ENTITIES.rowRollPointer,
      label: 'points with',
    },
    {
      id: INNODB_STRUCTURE_RELATIONS.bufferPoolCachesPage,
      kind: RelationKind.Caches,
      source: INNODB_STRUCTURE_ENTITIES.bufferPool,
      target: INNODB_STRUCTURE_ENTITIES.page,
      label: 'caches',
    },
    {
      id: INNODB_STRUCTURE_RELATIONS.bufferPoolUsesAdaptiveHash,
      kind: RelationKind.Caches,
      source: INNODB_STRUCTURE_ENTITIES.bufferPool,
      target: INNODB_STRUCTURE_ENTITIES.adaptiveHashIndex,
      label: 'is indexed by',
    },
    {
      id: INNODB_STRUCTURE_RELATIONS.bufferPoolUsesChangeBuffer,
      kind: RelationKind.Caches,
      source: INNODB_STRUCTURE_ENTITIES.bufferPool,
      target: INNODB_STRUCTURE_ENTITIES.changeBuffer,
      label: 'merges',
    },
    {
      id: INNODB_STRUCTURE_RELATIONS.adaptiveHashIndexesBufferPool,
      kind: RelationKind.Caches,
      source: INNODB_STRUCTURE_ENTITIES.adaptiveHashIndex,
      target: INNODB_STRUCTURE_ENTITIES.bufferPool,
      label: 'indexes hot pages',
    },
    {
      id: INNODB_STRUCTURE_RELATIONS.changeBufferCachesSecondaryChanges,
      kind: RelationKind.Caches,
      source: INNODB_STRUCTURE_ENTITIES.changeBuffer,
      target: INNODB_STRUCTURE_ENTITIES.bufferPool,
      label: 'buffers changes',
    },
    {
      id: INNODB_STRUCTURE_RELATIONS.logBufferFlushesRedo,
      kind: RelationKind.FlushesTo,
      source: INNODB_STRUCTURE_ENTITIES.logBuffer,
      target: INNODB_STRUCTURE_ENTITIES.redoLog,
      label: 'flushes',
    },
    {
      id: INNODB_STRUCTURE_RELATIONS.bufferPoolFlushesThroughOsCache,
      kind: RelationKind.FlushesTo,
      source: INNODB_STRUCTURE_ENTITIES.bufferPool,
      target: INNODB_STRUCTURE_ENTITIES.osCache,
      label: 'writes via',
    },
    {
      id: INNODB_STRUCTURE_RELATIONS.osCacheFlushesSystemTablespace,
      kind: RelationKind.FlushesTo,
      source: INNODB_STRUCTURE_ENTITIES.osCache,
      target: INNODB_STRUCTURE_ENTITIES.systemTablespace,
      label: 'flushes',
    },
    {
      id: INNODB_STRUCTURE_RELATIONS.bufferPoolWritesDoublewrite,
      kind: RelationKind.WritesTo,
      source: INNODB_STRUCTURE_ENTITIES.bufferPool,
      target: INNODB_STRUCTURE_ENTITIES.doublewriteFiles,
      label: 'writes pages first',
    },
    {
      id: INNODB_STRUCTURE_RELATIONS.systemTablespaceStoresChangeBuffer,
      kind: RelationKind.Contains,
      source: INNODB_STRUCTURE_ENTITIES.systemTablespace,
      target: INNODB_STRUCTURE_ENTITIES.changeBuffer,
      label: 'stores',
    },
    {
      id: INNODB_STRUCTURE_RELATIONS.undoStoresRollbacks,
      kind: RelationKind.WritesTo,
      source: INNODB_STRUCTURE_ENTITIES.rowRollPointer,
      target: INNODB_STRUCTURE_ENTITIES.undoTablespaces,
      label: 'points to undo',
    },
    {
      id: INNODB_STRUCTURE_RELATIONS.redoProtectsRecovery,
      kind: RelationKind.WritesTo,
      source: INNODB_STRUCTURE_ENTITIES.page,
      target: INNODB_STRUCTURE_ENTITIES.redoLog,
      label: 'protected by redo',
    },
    {
      id: INNODB_STRUCTURE_RELATIONS.tableLivesInFilePerTable,
      kind: RelationKind.Contains,
      source: INNODB_STRUCTURE_ENTITIES.tablespace,
      target: INNODB_STRUCTURE_ENTITIES.filePerTableTablespaces,
      label: 'can be',
    },
    {
      id: INNODB_STRUCTURE_RELATIONS.tableLivesInGeneralTablespace,
      kind: RelationKind.Contains,
      source: INNODB_STRUCTURE_ENTITIES.tablespace,
      target: INNODB_STRUCTURE_ENTITIES.generalTablespaces,
      label: 'can be',
    },
    {
      id: INNODB_STRUCTURE_RELATIONS.tempLivesInTemporaryTablespace,
      kind: RelationKind.Contains,
      source: INNODB_STRUCTURE_ENTITIES.tablespace,
      target: INNODB_STRUCTURE_ENTITIES.temporaryTablespaces,
      label: 'temporary kind',
    },
  ],
};

export const innodbStructureProcess: MechanismProcess = {
  id: processId('innodb.structure.process'),
  label: 'InnoDB structure map',
  steps: [
    {
      id: processStepId('innodb.structure.step.tablespace'),
      label: 'Tablespace is the top physical container',
      relationId: INNODB_STRUCTURE_RELATIONS.engineOwnsTablespace,
      entityVisuals: [
        { entityId: INNODB_STRUCTURE_ENTITIES.innodb, tone: VisualTone.Active, weight: VisualWeight.Normal },
        { entityId: INNODB_STRUCTURE_ENTITIES.tablespace, tone: VisualTone.Active, weight: VisualWeight.Strong },
      ],
      relationVisuals: [
        { relationId: INNODB_STRUCTURE_RELATIONS.engineOwnsTablespace, tone: VisualTone.Active, weight: VisualWeight.Strong },
      ],
    },
    {
      id: processStepId('innodb.structure.step.segment'),
      label: 'Tablespaces contain segments',
      relationId: INNODB_STRUCTURE_RELATIONS.tablespaceContainsSegment,
      entityVisuals: [
        { entityId: INNODB_STRUCTURE_ENTITIES.tablespace, tone: VisualTone.Traversed, weight: VisualWeight.Normal },
        { entityId: INNODB_STRUCTURE_ENTITIES.segment, tone: VisualTone.Traversed, weight: VisualWeight.Strong },
      ],
      relationVisuals: [
        { relationId: INNODB_STRUCTURE_RELATIONS.tablespaceContainsSegment, tone: VisualTone.Traversed, weight: VisualWeight.Strong },
      ],
    },
    {
      id: processStepId('innodb.structure.step.extent'),
      label: 'Segments allocate extents',
      relationId: INNODB_STRUCTURE_RELATIONS.segmentContainsExtent,
      entityVisuals: [
        { entityId: INNODB_STRUCTURE_ENTITIES.segment, tone: VisualTone.Traversed, weight: VisualWeight.Normal },
        { entityId: INNODB_STRUCTURE_ENTITIES.extent, tone: VisualTone.Traversed, weight: VisualWeight.Strong },
      ],
      relationVisuals: [
        { relationId: INNODB_STRUCTURE_RELATIONS.segmentContainsExtent, tone: VisualTone.Traversed, weight: VisualWeight.Strong },
      ],
    },
    {
      id: processStepId('innodb.structure.step.page'),
      label: 'Extents group pages, the I/O and cache unit',
      relationId: INNODB_STRUCTURE_RELATIONS.extentContainsPage,
      entityVisuals: [
        { entityId: INNODB_STRUCTURE_ENTITIES.extent, tone: VisualTone.Active, weight: VisualWeight.Normal },
        { entityId: INNODB_STRUCTURE_ENTITIES.page, tone: VisualTone.Active, weight: VisualWeight.Strong },
      ],
      relationVisuals: [
        { relationId: INNODB_STRUCTURE_RELATIONS.extentContainsPage, tone: VisualTone.Active, weight: VisualWeight.Strong },
      ],
    },
    {
      id: processStepId('innodb.structure.step.row'),
      label: 'Pages store rows with hidden MVCC fields',
      relationId: INNODB_STRUCTURE_RELATIONS.pageContainsRow,
      entityVisuals: [
        { entityId: INNODB_STRUCTURE_ENTITIES.page, tone: VisualTone.Active, weight: VisualWeight.Normal },
        { entityId: INNODB_STRUCTURE_ENTITIES.row, tone: VisualTone.Mutated, weight: VisualWeight.Strong },
        { entityId: INNODB_STRUCTURE_ENTITIES.rowTrxId, tone: VisualTone.Guarded, weight: VisualWeight.Normal },
        { entityId: INNODB_STRUCTURE_ENTITIES.rowRollPointer, tone: VisualTone.Guarded, weight: VisualWeight.Normal },
      ],
      relationVisuals: [
        { relationId: INNODB_STRUCTURE_RELATIONS.pageContainsRow, tone: VisualTone.Mutated, weight: VisualWeight.Strong },
        { relationId: INNODB_STRUCTURE_RELATIONS.rowContainsTrxId, tone: VisualTone.Guarded, weight: VisualWeight.Soft },
        { relationId: INNODB_STRUCTURE_RELATIONS.rowContainsRollPointer, tone: VisualTone.Guarded, weight: VisualWeight.Soft },
      ],
    },
    {
      id: processStepId('innodb.structure.step.buffer-pool'),
      label: 'Buffer Pool caches pages in memory',
      relationId: INNODB_STRUCTURE_RELATIONS.bufferPoolCachesPage,
      entityVisuals: [
        { entityId: INNODB_STRUCTURE_ENTITIES.bufferPool, tone: VisualTone.Active, weight: VisualWeight.Strong },
        { entityId: INNODB_STRUCTURE_ENTITIES.page, tone: VisualTone.Active, weight: VisualWeight.Normal },
        { entityId: INNODB_STRUCTURE_ENTITIES.adaptiveHashIndex, tone: VisualTone.Traversed, weight: VisualWeight.Normal },
      ],
      relationVisuals: [
        { relationId: INNODB_STRUCTURE_RELATIONS.bufferPoolCachesPage, tone: VisualTone.Active, weight: VisualWeight.Strong },
        { relationId: INNODB_STRUCTURE_RELATIONS.adaptiveHashIndexesBufferPool, tone: VisualTone.Traversed, weight: VisualWeight.Soft },
      ],
    },
    {
      id: processStepId('innodb.structure.step.change-buffer'),
      label: 'Change Buffer delays secondary-index page work',
      relationId: INNODB_STRUCTURE_RELATIONS.changeBufferCachesSecondaryChanges,
      entityVisuals: [
        { entityId: INNODB_STRUCTURE_ENTITIES.changeBuffer, tone: VisualTone.Mutated, weight: VisualWeight.Strong },
        { entityId: INNODB_STRUCTURE_ENTITIES.bufferPool, tone: VisualTone.Active, weight: VisualWeight.Normal },
        { entityId: INNODB_STRUCTURE_ENTITIES.systemTablespace, tone: VisualTone.Persisted, weight: VisualWeight.Normal },
      ],
      relationVisuals: [
        { relationId: INNODB_STRUCTURE_RELATIONS.changeBufferCachesSecondaryChanges, tone: VisualTone.Mutated, weight: VisualWeight.Strong },
        { relationId: INNODB_STRUCTURE_RELATIONS.systemTablespaceStoresChangeBuffer, tone: VisualTone.Persisted, weight: VisualWeight.Soft },
      ],
    },
    {
      id: processStepId('innodb.structure.step.page-flush'),
      label: 'Dirty pages flush through the OS path and doublewrite guard',
      relationId: INNODB_STRUCTURE_RELATIONS.bufferPoolFlushesThroughOsCache,
      entityVisuals: [
        { entityId: INNODB_STRUCTURE_ENTITIES.bufferPool, tone: VisualTone.Mutated, weight: VisualWeight.Normal },
        { entityId: INNODB_STRUCTURE_ENTITIES.osCache, tone: VisualTone.Persisted, weight: VisualWeight.Normal },
        { entityId: INNODB_STRUCTURE_ENTITIES.doublewriteFiles, tone: VisualTone.Persisted, weight: VisualWeight.Strong },
        { entityId: INNODB_STRUCTURE_ENTITIES.systemTablespace, tone: VisualTone.Persisted, weight: VisualWeight.Normal },
      ],
      relationVisuals: [
        { relationId: INNODB_STRUCTURE_RELATIONS.bufferPoolFlushesThroughOsCache, tone: VisualTone.Persisted, weight: VisualWeight.Strong },
        { relationId: INNODB_STRUCTURE_RELATIONS.osCacheFlushesSystemTablespace, tone: VisualTone.Persisted, weight: VisualWeight.Normal },
        { relationId: INNODB_STRUCTURE_RELATIONS.bufferPoolWritesDoublewrite, tone: VisualTone.Persisted, weight: VisualWeight.Normal },
      ],
    },
    {
      id: processStepId('innodb.structure.step.undo-redo'),
      label: 'Undo reconstructs old row versions; redo protects recovery',
      relationId: INNODB_STRUCTURE_RELATIONS.undoStoresRollbacks,
      entityVisuals: [
        { entityId: INNODB_STRUCTURE_ENTITIES.rowRollPointer, tone: VisualTone.Guarded, weight: VisualWeight.Normal },
        { entityId: INNODB_STRUCTURE_ENTITIES.undoTablespaces, tone: VisualTone.Guarded, weight: VisualWeight.Strong },
        { entityId: INNODB_STRUCTURE_ENTITIES.redoLog, tone: VisualTone.Persisted, weight: VisualWeight.Strong },
      ],
      relationVisuals: [
        { relationId: INNODB_STRUCTURE_RELATIONS.undoStoresRollbacks, tone: VisualTone.Guarded, weight: VisualWeight.Strong },
        { relationId: INNODB_STRUCTURE_RELATIONS.redoProtectsRecovery, tone: VisualTone.Persisted, weight: VisualWeight.Normal },
      ],
    },
    {
      id: processStepId('innodb.structure.step.redo-flush'),
      label: 'Log Buffer flushes redo records to redo log files',
      relationId: INNODB_STRUCTURE_RELATIONS.logBufferFlushesRedo,
      entityVisuals: [
        { entityId: INNODB_STRUCTURE_ENTITIES.logBuffer, tone: VisualTone.Mutated, weight: VisualWeight.Strong },
        { entityId: INNODB_STRUCTURE_ENTITIES.redoLog, tone: VisualTone.Persisted, weight: VisualWeight.Strong },
      ],
      relationVisuals: [
        { relationId: INNODB_STRUCTURE_RELATIONS.logBufferFlushesRedo, tone: VisualTone.Persisted, weight: VisualWeight.Strong },
      ],
    },
    {
      id: processStepId('innodb.structure.step.tablespace-types'),
      label: 'Tablespaces branch into system, file-per-table, general and temporary files',
      relationId: INNODB_STRUCTURE_RELATIONS.tableLivesInFilePerTable,
      entityVisuals: [
        { entityId: INNODB_STRUCTURE_ENTITIES.systemTablespace, tone: VisualTone.Active, weight: VisualWeight.Normal },
        { entityId: INNODB_STRUCTURE_ENTITIES.filePerTableTablespaces, tone: VisualTone.Active, weight: VisualWeight.Strong },
        { entityId: INNODB_STRUCTURE_ENTITIES.generalTablespaces, tone: VisualTone.Active, weight: VisualWeight.Strong },
        { entityId: INNODB_STRUCTURE_ENTITIES.temporaryTablespaces, tone: VisualTone.Active, weight: VisualWeight.Strong },
      ],
      relationVisuals: [
        { relationId: INNODB_STRUCTURE_RELATIONS.tableLivesInFilePerTable, tone: VisualTone.Active, weight: VisualWeight.Normal },
        { relationId: INNODB_STRUCTURE_RELATIONS.tableLivesInGeneralTablespace, tone: VisualTone.Active, weight: VisualWeight.Normal },
        { relationId: INNODB_STRUCTURE_RELATIONS.tempLivesInTemporaryTablespace, tone: VisualTone.Active, weight: VisualWeight.Normal },
      ],
    },
  ],
};
