import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

function readProjectFile(filePath) {
  return fs.readFileSync(path.resolve(filePath), 'utf8');
}

const source = readProjectFile('src/panels/ExplanationCard.tsx');
const markdownSource = readProjectFile('src/panels/explanation/MarkdownView.tsx');
const domainLensSource = readProjectFile('src/panels/explanation/DomainLensPanel.tsx');
const projectionSource = readProjectFile('src/panels/explanation/ProjectionReferences.tsx');
const supertagSource = readProjectFile('src/panels/explanation/SupertagPanel.tsx');
const componentsCss = readProjectFile('src/styles/components.css');
const appSource = readProjectFile('src/App.tsx');
const typesSource = readProjectFile('src/types.ts');
const storeSource = readProjectFile('src/store/useGraph.ts');
const topBarSource = readProjectFile('src/layout/TopBar.tsx');
const supertagLibrarySource = readProjectFile('src/components/SupertagLibrary.tsx');
const databaseCss = readProjectFile('src/styles/database.css');
const explanationIndexSource = readProjectFile('src/core/ExplanationIndexView.tsx');
const explanationIndexModel = readProjectFile('src/knowledge/explanationIndex.ts');
const explanationIndexMutations = readProjectFile('src/knowledge/explanationIndexMutations.ts');
const supertagUtilsSource = readProjectFile('src/knowledge/supertags.ts');
const supertagMaterialsSource = readProjectFile('src/knowledge/supertagMaterials.ts');

assert.match(source, /findTreeNodeById/);
assert.match(source, /collectTreeReferencesByNodeRef/);
assert.doesNotMatch(source, /activeContextTreeId/);
assert.doesNotMatch(source, /contextEnvironmentLabel\(activeContext\)/);
assert.doesNotMatch(source, /className="context-env-chip"/);
assert.match(source, /explanation-card-body--content-only/);
assert.doesNotMatch(source, /className="card-tabs"/);
assert.doesNotMatch(source, /<DomainLensPanel/);
assert.doesNotMatch(source, /function TabTreeItem/);
assert.match(source, /<SupertagPanel/);
assert.match(source, /<ProjectionReferences/);
assert.match(source, /<MarkdownView/);
assert.match(source, /updatePathSupplementContent\(activeContext\.treeNodeId/);
assert.match(source, /const activePathTab =/);
assert.doesNotMatch(source, /id: 'path',\s*label:/);
assert.doesNotMatch(source, /addKnowledgeTab/);
assert.doesNotMatch(source, /removeKnowledgeTab/);
assert.doesNotMatch(source, /renameKnowledgeTab/);
assert.match(source, /const activeTags =/);
assert.match(source, /ExplanationSelectionKind\.Root[\s\S]*nodeMeta\?\.tags \?\? \[\]/);
assert.match(source, /activePage\?\.tags \?\? activeTab\?\.tags \?\? \[\]/);
assert.match(source, /<SupertagPanel tags=\{activeTags\} onOpenTag=\{openSupertag\} \/>/);
assert.doesNotMatch(source, /activeSupertag/);
assert.doesNotMatch(source, /className="card-tab-add"/);
assert.doesNotMatch(source, /function ItemActionMenu/);
assert.doesNotMatch(source, /className="explanation-item-menu-trigger"/);
assert.doesNotMatch(source, /className="explanation-item-menu"/);
assert.match(storeSource, /addKnowledgeTab: \(knowledgeId: string, label: string, parentTabId\?: string \| null\) => string \| null/);
assert.match(storeSource, /removeKnowledgeTab: \(knowledgeId: string, tabId: string\) => void/);
assert.match(storeSource, /renameKnowledgeTab: \(knowledgeId: string, tabId: string, label: string\) => void/);
assert.match(storeSource, /const newTab: ExplanationTab = \{ id: tabId, label: trimmedLabel, content: '' \}/);
assert.match(storeSource, /tabs: \[\.\.\.existing\.card\.tabs, newTab\]/);
assert.match(storeSource, /if \(tabId === DEFINITION_TAB_ID && !isTopLevel\) return;/);
assert.doesNotMatch(storeSource, /if \(isTopLevel && existing\.card\.tabs\.length <= 1\) return;/);
assert.match(typesSource, /export interface ExplanationPage/);
assert.match(typesSource, /tags\?: string\[\]/);
assert.match(typesSource, /pages\?: ExplanationPage\[\]/);
assert.match(typesSource, /definitionPages\?: ExplanationPage\[\]/);
assert.match(storeSource, /addKnowledgeTabPage:\s*\([\s\S]*parentPageId\?: string \| null,[\s\S]*\) => string \| null/);
assert.match(storeSource, /removeKnowledgeTabPage: \(knowledgeId: string, tabId: string, pageId: string\) => void/);
assert.match(storeSource, /updateKnowledgeTabPage: \(knowledgeId: string, tabId: string, pageId: string, content: string\) => void/);
assert.doesNotMatch(source, /className="definition-pages definition-pages-multirow"/);
assert.doesNotMatch(source, /className="definition-page-add"/);
assert.doesNotMatch(source, /addKnowledgeTabPage/);
assert.match(source, /updateKnowledgeTabPage/);
assert.match(source, /updateKnowledgeRootContent/);
assert.match(source, /ExplanationSelectionKind\.Root[\s\S]*updateKnowledgeRootContent/);
assert.match(source, /explanation\.rootContent/);
assert.match(storeSource, /updateKnowledgeRootContent: \(knowledgeId: string, content: string\) => void/);
assert.match(storeSource, /rootContent: content/);
assert.match(typesSource, /rootContent\?: string/);
assert.doesNotMatch(source, /isVisibleExplanationTab/);
assert.match(source, /activeExplanationSelection/);
assert.match(source, /setActiveExplanationSelection/);
assert.match(source, /ExplanationSelectionKind\.Content/);
assert.match(source, /const suggestedLabel = selectedTreeNode\?\.name\.trim\(\) \?\? ''/);
assert.match(source, /const createLabel = \(newLabel\.trim\(\) \|\| suggestedLabel\)\.trim\(\)/);
assert.match(source, /addKnowledgeNode\(createLabel\)/);
assert.match(source, /linkTreeToKnowledge\(selectedTreeNodeId, id\)/);
assert.match(source, /selectTreeEntry\(selectedTreeNodeId\)/);
assert.match(source, /disabled=\{!createLabel\}/);
assert.doesNotMatch(source, /createKnowledgeAndLink/);
assert.doesNotMatch(source, /className="ec-meta-chips"/);
assert.doesNotMatch(source, /editingMeta/);
assert.doesNotMatch(source, /setEditingMeta/);
assert.doesNotMatch(source, /metaLabel/);
assert.doesNotMatch(source, /metaRole/);
assert.doesNotMatch(source, /metaTags/);
assert.doesNotMatch(source, /KnowledgeRole/);
assert.doesNotMatch(source, /function MarkdownView/);
assert.doesNotMatch(source, /function ProjectionReferences/);
assert.doesNotMatch(source, /function ContextCutGrid/);
assert.doesNotMatch(source, /supertagMode ===/);
assert.doesNotMatch(source, /Object\.values\(nodePool\)\.filter\(\(node\) => node\.tags/);

assert.match(markdownSource, /export default function MarkdownView/);
assert.match(domainLensSource, /export default function DomainLensPanel/);
assert.match(domainLensSource, /领域镜头/);
assert.match(domainLensSource, /contexts\.length/);
assert.match(domainLensSource, /activeSupertag/);
assert.match(domainLensSource, /className="supertag-panel domain-lens-supertag"/);
assert.match(domainLensSource, /supertagMode === 'compare'/);
assert.match(domainLensSource, /当前概念暂无目录引用/);
assert.match(domainLensSource, /showDetail && activeContext && !activeSupertag/);
assert.match(domainLensSource, /onOpenTreeContext\(activeContext\.treeNodeId\)/);
assert.match(domainLensSource, /className="domain-lens-grid"/);
assert.match(projectionSource, /export default function ProjectionReferences/);
assert.match(projectionSource, /MatrixProjection/);
assert.match(supertagSource, /export default function SupertagPanel/);
assert.match(supertagUtilsSource, /export function normalizeSupertag/);
assert.match(supertagUtilsSource, /export function normalizeSupertags/);
assert.match(supertagSource, /tags: readonly string\[\]/);
assert.match(supertagSource, /onOpenTag: \(tag: string\) => void/);
assert.match(supertagSource, /tags\.map\(\(tag\) =>/);
assert.match(supertagSource, /concept-supertag--link/);
assert.match(supertagSource, /\{tag\}/);
assert.doesNotMatch(supertagSource, /useState|useEffect/);
assert.doesNotMatch(supertagSource, /updateKnowledgeNodeMeta|onActiveSupertagChange/);
assert.match(supertagSource, /<button/);
assert.doesNotMatch(supertagSource, /<input/);
assert.match(supertagSource, /onClick=\{\(\) => onOpenTag\(tag\)\}/);
assert.match(componentsCss, /\.concept-supertag--link\s*\{/);
assert.match(domainLensSource, /可继续归纳父类/);
assert.match(domainLensSource, /抽象锚点/);
assert.match(domainLensSource, /父类候选/);

assert.match(typesSource, /export type AppView = 'universe' \| 'index' \| 'mechanism' \| 'database' \| 'questions' \| 'supertags'/);
assert.match(typesSource, /export enum ExplanationSelectionKind/);
assert.match(storeSource, /activeView: AppView/);
assert.match(storeSource, /setActiveView: \(view: AppView\) => void/);
assert.match(storeSource, /selectedSupertag: string \| null/);
assert.match(storeSource, /openSupertag: \(tag: string\) => void/);
assert.match(storeSource, /set\(\{ selectedSupertag, activeView: 'supertags' \}\)/);
assert.match(storeSource, /activeExplanationSelection: ExplanationSelection \| null/);
assert.match(storeSource, /setActiveExplanationSelection:/);
assert.match(topBarSource, /ReadonlyArray<\{[^}]*id: AppView/s);
assert.match(topBarSource, /label: '索引'[\s\S]*id: 'index'/);
assert.match(topBarSource, /Supertag库/);
assert.match(appSource, /activeView === 'index'/);
assert.match(appSource, /<ExplanationIndexView/);
assert.match(appSource, /activeView === 'supertags'/);
assert.match(appSource, /<SupertagLibrary/);
assert.match(supertagLibrarySource, /export default function SupertagLibrary/);
assert.match(supertagLibrarySource, /collectSupertagMaterialGroups\(nodePool\)/);
assert.match(supertagLibrarySource, /SupertagLibraryMode\.Compare/);
assert.match(supertagLibrarySource, /supertagMaterialSignature/);
assert.match(supertagLibrarySource, /group\.tag === selectedSupertag/);
assert.match(supertagLibrarySource, /openSupertag\(group\.tag\)/);
assert.match(supertagLibrarySource, /openCard\(material\.nodeId\)/);
assert.match(supertagLibrarySource, /setActiveExplanationSelection\(material\.selection\)/);
assert.match(supertagMaterialsSource, /export enum SupertagMaterialKind/);
assert.match(supertagMaterialsSource, /selection: ExplanationIndexSelection/);
assert.match(supertagMaterialsSource, /kind: ExplanationSelectionKind\.Root/);
assert.match(supertagMaterialsSource, /kind: ExplanationSelectionKind\.Content/);
assert.match(supertagMaterialsSource, /node\.tags/);
assert.match(supertagMaterialsSource, /tab\.tags/);
assert.match(supertagMaterialsSource, /page\.tags/);
assert.match(supertagMaterialsSource, /definitionPages/);
assert.match(supertagMaterialsSource, /collectPages/);
assert.match(supertagMaterialsSource, /collectTabs/);
assert.match(databaseCss, /\.supertag-library\s*\{/);
assert.match(databaseCss, /\.supertag-index-item\.is-active/);
assert.match(databaseCss, /\.supertag-material-grid\s*\{/);
assert.match(databaseCss, /\.supertag-comparison\s*\{/);

assert.doesNotMatch(appSource, /BottomBar/);
assert.doesNotMatch(appSource, /<footer className="toolbar"/);
assert.match(componentsCss, /\.markdown-view\s*\{[\s\S]*font-size:\s*14px/);
assert.match(componentsCss, /\.markdown-view p\s*\{[\s\S]*font-size:\s*14px/);
assert.match(componentsCss, /\.explanation-card-header--compact\s*\{[\s\S]*min-height:\s*28px/);
assert.match(componentsCss, /\.explanation-card-body--content-only\s*\{[\s\S]*display:\s*flex/);
assert.match(componentsCss, /\.explanation-editor\s*\{/);
assert.doesNotMatch(componentsCss, /\.supertag-wrap:hover \.supertag-remove/);
assert.match(componentsCss, /\.card-content\s*\{[\s\S]*min-width:\s*0/);
assert.doesNotMatch(componentsCss, /\.context-env-chip::after/);
assert.match(explanationIndexSource, /splitDirectionForDepth/);
assert.match(explanationIndexSource, /MatrixSplitDirection\.UpDown/);
assert.match(explanationIndexSource, /MatrixSplitDirection\.LeftRight/);
assert.match(explanationIndexSource, /setActiveExplanationSelection/);
assert.doesNotMatch(explanationIndexSource, /className="explanation-index-controls"/);
assert.match(explanationIndexSource, /className="explanation-index-editor"/);
assert.match(explanationIndexSource, /className="explanation-index-edit-trigger"/);
assert.match(explanationIndexSource, /className="explanation-index-paths"/);
assert.match(explanationIndexSource, /ExplanationSelectionKind\.Path/);
assert.match(explanationIndexSource, /onDoubleClick/);
assert.doesNotMatch(explanationIndexSource, /setExplanationIndexTags|tagDraft|normalizeSupertag/);
assert.doesNotMatch(explanationIndexSource, /explanation-index-cell-tags|explanation-index-editor-tags/);
assert.match(explanationIndexModel, /buildExplanationIndex/);
assert.match(explanationIndexModel, /explicitPagesForTab/);
assert.doesNotMatch(explanationIndexModel, /tags: page\.tags \?\? \[\]|tags: tab\.tags \?\? \[\]|rootTags/);
assert.match(explanationIndexMutations, /setExplanationIndexItemTags/);
assert.match(explanationIndexMutations, /childCount < 1/);
assert.doesNotMatch(explanationIndexMutations, /childCount < 2/);
assert.match(explanationIndexSource, /isRoot \? '＋子格' : '＋同级'/);
assert.match(storeSource, /setExplanationIndexTags:/);
assert.match(componentsCss, /\.explanation-index-node--up-down\s*\{[\s\S]*grid-template-columns/);
assert.match(componentsCss, /\.explanation-index-node--left-right\s*\{[\s\S]*grid-template-rows/);
assert.match(componentsCss, /\.explanation-index-children\.is-column\s*\{[\s\S]*flex-direction:\s*column/);
assert.match(componentsCss, /\.explanation-index-children\.is-row\s*\{[\s\S]*flex-direction:\s*row/);
assert.doesNotMatch(componentsCss, /\.explanation-index-cell-tag|\.explanation-index-editor-tags/);

console.log('explanation card binding checks passed');
