import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';

function readProjectFile(filePath) {
  return fs.readFileSync(path.resolve(filePath), 'utf8');
}

const source = readProjectFile('src/panels/ExplanationCard.tsx');
const markdownSource = readProjectFile('src/panels/explanation/MarkdownView.tsx');
const domainLensSource = readProjectFile('src/panels/explanation/DomainLensPanel.tsx');
const projectionSource = readProjectFile('src/panels/explanation/ProjectionReferences.tsx');
const supertagSource = readProjectFile('src/panels/explanation/SupertagPanel.tsx');
const titleMatrixSource = readProjectFile('src/panels/explanation/RecursiveTitleMatrix.tsx');
const componentsCss = readProjectFile('src/styles/components.css');
const appSource = readProjectFile('src/App.tsx');
const typesSource = readProjectFile('src/types.ts');
const storeSource = readProjectFile('src/store/useGraph.ts');
const topBarSource = readProjectFile('src/layout/TopBar.tsx');
const supertagLibrarySource = readProjectFile('src/components/SupertagLibrary.tsx');
const databaseCss = readProjectFile('src/styles/database.css');

assert.match(source, /findTreeNodeById/);
assert.match(source, /collectTreeReferencesByNodeRef/);
assert.match(source, /const \[activeContextTreeId, setActiveContextTreeId\]/);
assert.match(source, /contextEnvironmentLabel\(activeContext\)/);
assert.match(source, /className="context-env-chip"/);
assert.match(source, /className="explanation-card-body"/);
assert.match(source, /<RecursiveTitleMatrix/);
assert.doesNotMatch(source, /<DomainLensPanel/);
assert.match(source, /<SupertagPanel/);
assert.match(source, /<ProjectionReferences/);
assert.match(source, /<MarkdownView/);
assert.match(source, /updatePathSupplementContent\(activeContext\.treeNodeId/);
assert.match(source, /const pathTab: ExplanationTab \| null =\s*activeContextSupplement\?\.tabs\?\.\[0\] \?\? null/);
assert.doesNotMatch(source, /id: 'path',\s*label:/);
assert.match(source, /addKnowledgeTab/);
assert.match(source, /removeKnowledgeTab/);
assert.match(source, /renameKnowledgeTab/);
assert.match(source, /const \[activeSupertag, setActiveSupertag\]/);
assert.match(source, /activeSupertag=\{activeSupertag\}/);
assert.match(source, /onActiveSupertagChange=\{setActiveSupertag\}/);
assert.match(titleMatrixSource, /export default function RecursiveTitleMatrix/);
assert.match(titleMatrixSource, /depth % 2 === 0 \? 'column' : 'row'/);
assert.match(titleMatrixSource, /className="title-matrix-parent-rail"/);
assert.match(titleMatrixSource, /className="title-matrix-children" data-axis=\{axis\}/);
assert.match(titleMatrixSource, /className="title-matrix-leaf-title"/);
assert.match(titleMatrixSource, /onWeightChange\(node\.target, weight\)/);
assert.match(titleMatrixSource, /onMerge\(node\.target\)/);
assert.match(titleMatrixSource, /count === 1 \? label : `\$\{label\} \$\{index \+ 1\}`/);
assert.match(storeSource, /addKnowledgeTab: \(knowledgeId: string, label: string, parentTabId\?: string \| null\) => string \| null/);
assert.match(storeSource, /removeKnowledgeTab: \(knowledgeId: string, tabId: string\) => void/);
assert.match(storeSource, /renameKnowledgeTab: \(knowledgeId: string, tabId: string, label: string\) => void/);
assert.match(storeSource, /const newTab: ExplanationTab = \{ id: tabId, label: trimmedLabel, content: '' \}/);
assert.match(storeSource, /tabs: \[\.\.\.existing\.card\.tabs, newTab\]/);
assert.match(storeSource, /existing\.card\.tabs\.length <= 1/);
assert.match(typesSource, /export interface ExplanationPage/);
assert.match(typesSource, /weight\?: number/);
assert.match(typesSource, /export type ExplanationTitleTarget/);
assert.match(typesSource, /pages\?: ExplanationPage\[\]/);
assert.match(typesSource, /definitionPages\?: ExplanationPage\[\]/);
assert.match(storeSource, /addKnowledgeTabPage:\s*\([\s\S]*parentPageId\?: string \| null,[\s\S]*\) => string \| null/);
assert.match(storeSource, /removeKnowledgeTabPage: \(knowledgeId: string, tabId: string, pageId: string\) => void/);
assert.match(storeSource, /updateKnowledgeTabPage: \(knowledgeId: string, tabId: string, pageId: string, content: string\) => void/);
assert.doesNotMatch(source, /className="definition-pages definition-pages-multirow"/);
assert.match(source, /addKnowledgeTabPage/);
assert.match(source, /updateKnowledgeTabPage/);
assert.match(storeSource, /updateExplanationTitleWeight:/);
assert.match(storeSource, /mergeExplanationTitle:/);
assert.match(source, /const visibleTabs = explanation\?\.tabs \?\? \[\]/);
assert.doesNotMatch(source, /HIDDEN_LEGACY_TAB_IDS/);
assert.match(source, /const suggestedLabel = selectedTreeNode\?\.name\.trim\(\) \?\? ''/);
assert.match(source, /const createLabel = \(newLabel\.trim\(\) \|\| suggestedLabel\)\.trim\(\)/);
assert.match(source, /addKnowledgeNode\(createLabel\)/);
assert.match(source, /linkTreeToKnowledge\(selectedTreeNodeId, id\)/);
assert.match(source, /selectTreeEntry\(selectedTreeNodeId\)/);
assert.match(source, /disabled=\{!createLabel\}/);
assert.doesNotMatch(source, /createKnowledgeAndLink/);
assert.doesNotMatch(source, /className="ec-meta-chips"/);
assert.doesNotMatch(source, /editingMeta/);
assert.doesNotMatch(source, /setEditingMeta/);
assert.doesNotMatch(source, /metaLabel/);
assert.doesNotMatch(source, /metaRole/);
assert.doesNotMatch(source, /metaTags/);
assert.doesNotMatch(source, /KnowledgeRole/);
assert.doesNotMatch(source, /function MarkdownView/);
assert.doesNotMatch(source, /function ProjectionReferences/);
assert.doesNotMatch(source, /function ContextCutGrid/);
assert.doesNotMatch(source, /supertagMode ===/);
assert.doesNotMatch(source, /Object\.values\(nodePool\)\.filter\(\(node\) => node\.tags/);

assert.match(markdownSource, /export default function MarkdownView/);
assert.match(domainLensSource, /export default function DomainLensPanel/);
assert.match(domainLensSource, /领域镜头/);
assert.match(domainLensSource, /contexts\.length/);
assert.match(domainLensSource, /activeSupertag/);
assert.match(domainLensSource, /className="supertag-panel domain-lens-supertag"/);
assert.match(domainLensSource, /supertagMode === 'compare'/);
assert.match(domainLensSource, /当前概念暂无目录引用/);
assert.match(domainLensSource, /showDetail && activeContext && !activeSupertag/);
assert.match(domainLensSource, /onOpenTreeContext\(activeContext\.treeNodeId\)/);
assert.match(domainLensSource, /className="domain-lens-grid"/);
assert.match(projectionSource, /export default function ProjectionReferences/);
assert.match(projectionSource, /MatrixProjection/);
assert.match(supertagSource, /export default function SupertagPanel/);
assert.match(supertagSource, /function normalizeSupertag/);
assert.match(supertagSource, /const \[isAddingSupertag, setIsAddingSupertag\]/);
assert.match(supertagSource, /onActiveSupertagChange/);
assert.match(supertagSource, /activeSupertag === tag \? '' : tag/);
assert.match(supertagSource, /updateKnowledgeNodeMeta\(node\.id, \{ tags \}\)/);
assert.match(supertagSource, /className=\{`concept-supertag/);
assert.match(supertagSource, /\{tag\}/);
assert.doesNotMatch(supertagSource, /#\$\{tag\}/);
assert.doesNotMatch(supertagSource, /#\$\{activeSupertag\}/);
assert.doesNotMatch(supertagSource, /className=\{`supertag-panel/);
assert.doesNotMatch(supertagSource, /!\s*compact\s*&&\s*activeSupertag/);
assert.doesNotMatch(supertagSource, /supertag-panel--compact/);
assert.match(supertagSource, /title=\{`移除 supertag: \$\{tag\}`\}/);
assert.match(supertagSource, /aria-label="保存 supertag"/);
assert.match(supertagSource, /title="保存 supertag"/);
assert.doesNotMatch(supertagSource, /supertagMode === 'compare'/);
assert.doesNotMatch(supertagSource, /supertagMode === 'summarize'/);
assert.doesNotMatch(supertagSource, /同概念抽取/);
assert.doesNotMatch(supertagSource, /共享这个 supertag/);
assert.match(supertagSource, /supertag 锚点/);
assert.match(domainLensSource, /可继续归纳父类/);
assert.match(domainLensSource, /抽象锚点/);
assert.match(domainLensSource, /父类候选/);

assert.match(typesSource, /export type AppView = 'universe' \| 'mechanism' \| 'database' \| 'questions' \| 'supertags'/);
assert.match(storeSource, /activeView: AppView/);
assert.match(storeSource, /setActiveView: \(view: AppView\) => void/);
assert.match(topBarSource, /ReadonlyArray<\{[^}]*id: AppView/s);
assert.match(topBarSource, /Supertag库/);
assert.match(appSource, /activeView === 'supertags'/);
assert.match(appSource, /<SupertagLibrary/);
assert.match(supertagLibrarySource, /export default function SupertagLibrary/);
assert.match(supertagLibrarySource, /node\.tags\?\.forEach/);
assert.match(supertagLibrarySource, /openCard\(node\.id\)/);
assert.match(databaseCss, /\.supertag-library\s*\{/);
assert.match(databaseCss, /\.supertag-index-item\.is-active/);
assert.match(databaseCss, /\.supertag-material-grid\s*\{/);

assert.doesNotMatch(appSource, /BottomBar/);
assert.doesNotMatch(appSource, /<footer className="toolbar"/);
assert.match(componentsCss, /\.markdown-view\s*\{[\s\S]*font-size:\s*14px/);
assert.match(componentsCss, /\.markdown-view p\s*\{[\s\S]*font-size:\s*14px/);
assert.match(componentsCss, /\.explanation-card-header--compact\s*\{[\s\S]*min-height:\s*28px/);
assert.match(componentsCss, /\.explanation-card-body\s*\{[\s\S]*flex-direction:\s*column/);
assert.match(componentsCss, /\.recursive-title-matrix-scroll\s*\{/);
assert.match(componentsCss, /\.title-matrix-parent-rail\s*\{[\s\S]*flex:\s*0 0 30px/);
assert.match(componentsCss, /\.title-matrix-children\[data-axis='column'\]/);
assert.match(componentsCss, /\.title-matrix-children\[data-axis='row'\]/);
assert.match(componentsCss, /writing-mode:\s*vertical-rl/);
assert.match(componentsCss, /\.explanation-editor\s*\{/);
assert.match(componentsCss, /\.title-matrix-tools-trigger\s*\{[\s\S]*opacity:\s*0/);
assert.match(componentsCss, /\.title-matrix-tools-menu\s*\{/);
assert.match(componentsCss, /\.supertag-wrap:hover \.supertag-remove/);
assert.match(componentsCss, /\.card-content\s*\{[\s\S]*min-width:\s*0/);
assert.doesNotMatch(componentsCss, /\.context-env-chip::after/);

console.log('explanation card binding checks passed');
